### PR TITLE
sorta fix http2

### LINKED ISSUE #313: node v8.8 - HTTP2 issue?
Having some issues with upgrade to node 8.8

Bankai falls over when a website reloads ... I don't get much more in the logs other than an ELIFECYCLE error.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! descartes@1.0.0 dev: `bankai start index.js`
npm ERR! Exit status 1
```

### PR DESCRIPTION
**Pull request by yoshuawuyts**
As per https://github.com/nodejs/node/issues/16666, this sorta fixes http/2 support. It's a step up from where we're at right now. If this turns out to be too unstable, we should disable http2 by default for now, and perhaps make it opt-in until it further stabilizes, but I suggest we wait and see for a bit.

Closes #313. Thanks!

### CODE REVIEW

File: http.js [hunk 1]
```diff
@@ -192,14 +192,9 @@ function start (entry, opts) {
       res.write(`id:${id++}\ndata:{ "type:": "heartbeat" }\n\n`)
```
Comment (apapirovski) [inline http.js]: Just quoting myself :)

> you could add a little extra safety check to write that only fires if !res.finished.

Comment (yoshuawuyts) [reply http.js]: That's a great idea; updating!
